name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'develop']

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm run lint
  check:
    name: 'Svelte Check'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm run check

  test:
    name: 'Test'
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - name: Install Playwright browsers
        # Ensure Playwright downloads required browser binaries on the runner
        run: pnpm exec playwright install --with-deps
      - run: pnpm run test

  build:
    name: 'Build'
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, '24.x']
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm run build
